configuration:
  resources:
    - type: "open-ai-configuration"
      id: "openai"
      name: "OpenAI Azure configuration"
      configuration:
        url: "${secrets.open-ai.url}"
        access-key: "${secrets.open-ai.access-key}"
        provider: "${secrets.open-ai.provider}"
    - type: "datasource"
      id: "database"
      name: "AstraDatasource"
      configuration:
        service: "astra"
        clientId: "token"
        secret: "${ secrets.astra-langchain.token }"
        database: "${secrets.astra-langchain.database}"
        database-id: "${secrets.astra-langchain.database-id}"
        token: "${secrets.astra-langchain.token}"
        environment: "PROD"