name: "LangChain S3 source"
topics:
  - name: "questions-topic"
    creation-mode: create-if-not-exists
  - name: "answers-topic"
    creation-mode: create-if-not-exists
pipeline:
  - name: "Implemented a cha1t-bot using OpenAI and LangChain"
    id: "chatbot"
    type: "python-processor"
    input: "questions-topic"
    output: "answers-topic"
    errors:
      on-failure: "skip"
    configuration:
      className: "langchain_chat.LangChainChat"
      astra-db-keyspace: "${ secrets.astra-langchain.keyspace }"
      astra-db-table: "${ secrets.astra-langchain.table }"
      environment:
        - key: "LANGCHAIN_TRACING_V2"
          value: "true"
        - key: "LANGCHAIN_ENDPOINT"
          value: "${ secrets.lang-smith.api-url }"
        - key: "LANGCHAIN_API_KEY"
          value: "${ secrets.lang-smith.api-key }"